spin_version = "1"
authors = ["Chris Matteson"]
description = "hello-world"
name = "hello-world"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = "spin_static_fs.wasm"
id = "fs"
files = [ { source = "out/", destination = "/" } ]
[component.trigger]
route = "/..."